# Generated by Django 5.0.6 on 2026-05-22 17:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Taux de pénalité (% / mois)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Format: ACQ-ANNEE-XXXXXXXX', max_length=32, unique=True)),
                ('seller_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom du vendeur (si pas client)')),
                ('acquired_on', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisitions', to='lots.lot')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acquisitions_as_seller', to='clients.client')),
            ],
            options={
                'ordering': ('-acquired_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('due_on', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'À échoir'), ('partial', 'Partiellement payée'), ('paid', 'Soldée'), ('overdue', 'En retard')], default='pending', max_length=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='transactions.paymentplan')),
            ],
            options={
                'ordering': ('plan', 'position'),
                'unique_together': {('plan', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Format: VTE-ANNEE-XXXXXXXX', max_length=32, unique=True)),
                ('sold_on', models.DateField(default=django.utils.timezone.localdate)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix de vente')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Remise')),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('payment_mode', models.CharField(choices=[('cash', 'Comptant'), ('installment', 'Échelonné')], default='cash', max_length=16)),
                ('down_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Apport initial')),
                ('installment_count', models.PositiveSmallIntegerField(default=1, verbose_name="Nombre d'échéances")),
                ('installment_frequency_days', models.PositiveSmallIntegerField(default=30, verbose_name='Fréquence (jours)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('reserved', 'Réservé'), ('in_progress', 'En cours de paiement'), ('completed', 'Soldée'), ('cancelled', 'Annulée'), ('litigation', 'En litige')], db_index=True, default='draft', max_length=16)),
                ('contract_signed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_agent', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='lots.lot')),
            ],
            options={
                'ordering': ('-sold_on', '-id'),
            },
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='transactions.sale'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, help_text='Format: REC-AAAAMMJJ-XXXXXXXX', max_length=32, unique=True)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode')),
                ('reference', models.CharField(blank=True, default='', help_text='N° de chèque, ref Mobile Money, etc.', max_length=120, verbose_name='Réf. transaction')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_void', models.BooleanField(default=False)),
                ('voided_on', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=200)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('integrity_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='transactions.installment')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.sale')),
            ],
            options={
                'ordering': ('-paid_on', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'sold_on'], name='transaction_status_1c4273_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale', 'paid_on'], name='transaction_sale_id_eafb17_idx'),
        ),
    ]
