# Generated by Django 5.0.6 on 2026-05-22 18:25

import apps.transactions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('signed_contract', 'Contrat signé'), ('buyer_id', "Pièce d'identité de l'acheteur"), ('buyer_proof_of_address', 'Justificatif de domicile'), ('seller_document', 'Document du vendeur'), ('payment_proof', 'Preuve de paiement'), ('cadastral', 'Plan cadastral / titre'), ('power_of_attorney', 'Procuration'), ('other', 'Autre')], max_length=32, verbose_name='Type')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('file', models.FileField(upload_to=apps.transactions.models._sale_doc_path)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transactions.sale')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
