# Generated by Django 5.0.6 on 2026-05-22 18:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_saledocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('reserved', 'Réservé'), ('in_progress', 'En cours de paiement'), ('completed', 'Soldée'), ('cancelled', 'Annulée'), ('litigation', 'En litige'), ('withdrawn_buyer', 'Désistement acheteur'), ('withdrawn_seller', 'Désistement vendeur')], db_index=True, default='draft', max_length=16),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(choices=[('buyer', 'Acheteur'), ('seller', 'Vendeur')], max_length=10)),
                ('declared_on', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.TextField(verbose_name='Motif détaillé')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant retenu sur les versements déjà encaissés.', max_digits=14, verbose_name='Pénalité retenue')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant à rembourser')),
                ('refund_completed', models.BooleanField(default=False)),
                ('refund_completed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='transactions.sale')),
            ],
            options={
                'verbose_name': 'Désistement',
                'verbose_name_plural': 'Désistements',
            },
        ),
    ]
