# Generated by Django 5.0.6 on 2026-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_sale_status_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_refund',
            field=models.BooleanField(default=False, help_text="Mouvement sortant : remboursement au client lors d'un désistement.", verbose_name='Remboursement'),
        ),
    ]
