# Generated by Django 5.0.6 on 2026-05-22 17:22

import apps.lots.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Ville')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=80, verbose_name='Pays')),
                ('region', models.CharField(blank=True, default='', max_length=120, verbose_name='Région')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, help_text='Code unique sémantique, attribué automatiquement si vide. Format: LOT-VILLE-ANNEE-XXXXXXXX.', max_length=48, unique=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=200, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('lot_type', models.CharField(choices=[('residential', 'Résidentiel'), ('commercial', 'Commercial'), ('industrial', 'Industriel'), ('agricultural', 'Agricole'), ('mixed', 'Mixte')], default='residential', max_length=24, verbose_name='Type')),
                ('cadastral_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='Référence cadastrale')),
                ('surface_m2', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Surface (m²)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('polygon', models.JSONField(blank=True, help_text='Tableau de coordonnées [lng, lat] délimitant le lot.', null=True, verbose_name='Polygone (GeoJSON)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Coût d'acquisition initial.", max_digits=14, verbose_name="Prix d'achat")),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix de vente affiché')),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='Devise')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('sold', 'Vendu'), ('litigation', 'En litige'), ('off_market', 'Retiré du marché')], db_index=True, default='available', max_length=24, verbose_name='Statut')),
                ('has_water', models.BooleanField(default=False, verbose_name='Eau')),
                ('has_electricity', models.BooleanField(default=False, verbose_name='Électricité')),
                ('has_road_access', models.BooleanField(default=False, verbose_name='Voirie')),
                ('has_sewage', models.BooleanField(default=False, verbose_name='Assainissement')),
                ('has_internet', models.BooleanField(default=False, verbose_name='Internet')),
                ('has_title_deed', models.BooleanField(default=False, verbose_name='Titre foncier')),
                ('notes', models.TextField(blank=True, default='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lots.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LotPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.lots.models._lot_photo_path)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lots.lot')),
            ],
            options={
                'ordering': ('-is_primary', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Quartier')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neighborhoods', to='lots.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ('city__name', 'name'),
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='lots.neighborhood'),
        ),
        migrations.CreateModel(
            name='UtilityConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('water', 'Eau'), ('electricity', 'Électricité'), ('road', 'Voirie'), ('sewage', 'Assainissement'), ('internet', 'Internet'), ('gas', 'Gaz')], max_length=24)),
                ('is_connected', models.BooleanField(default=False)),
                ('operator', models.CharField(blank=True, default='', max_length=120)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('connection_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='lots.lot')),
            ],
            options={
                'ordering': ('lot', 'kind'),
            },
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['status', 'city'], name='lots_lot_status_2d3c16_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['city', 'neighborhood'], name='lots_lot_city_id_f1a07d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='utilityconnection',
            unique_together={('lot', 'kind')},
        ),
    ]
