# Generated by Django 5.0.6 on 2026-05-22 18:43

import apps.lots.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('title_deed', 'Titre foncier'), ('cadastral_plan', 'Plan cadastral'), ('land_survey', 'Levé topographique'), ('purchase_deed', "Acte d'achat"), ('evaluation', 'Évaluation'), ('building_permit', 'Permis de construire'), ('occupancy_permit', "Permis d'occupation"), ('aerial_photo', 'Photo aérienne'), ('utility_letter', 'Attestation de viabilisation'), ('other', 'Autre')], max_length=32, verbose_name='Type')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('file', models.FileField(upload_to=apps.lots.models._lot_doc_path)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lots.lot')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
