# Generated by Django 5.0.6 on 2026-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_lotdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='ilot',
            field=models.CharField(blank=True, default='', help_text="Numero / code d'ilot dans le lotissement (ex: A, 12, IL-04).", max_length=32, verbose_name='Ilot'),
        ),
        migrations.AddField(
            model_name='lot',
            name='lot_number',
            field=models.CharField(blank=True, default='', help_text='Numero du lot dans son ilot (ex: 5, 12B).', max_length=32, verbose_name='N° de lot'),
        ),
        migrations.AddField(
            model_name='lot',
            name='region',
            field=models.CharField(blank=True, default='', help_text='Region administrative.', max_length=120, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='lot',
            name='subdivision_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom du lotissement'),
        ),
        migrations.AddField(
            model_name='lot',
            name='village',
            field=models.CharField(blank=True, default='', help_text='Nom du village si different du quartier.', max_length=120, verbose_name='Village'),
        ),
    ]
