# Generated by Django 5.0.6 on 2026-05-22 17:22

import apps.clients.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Format: CLT-ANNEE-XXXXXXXX', max_length=32, unique=True, verbose_name='Code client')),
                ('kind', models.CharField(choices=[('individual', 'Particulier'), ('company', 'Entreprise')], default='individual', max_length=16, verbose_name='Type')),
                ('first_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Nom')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Raison sociale')),
                ('company_rccm', models.CharField(blank=True, default='', max_length=80, verbose_name='RCCM')),
                ('contact_person', models.CharField(blank=True, default='', max_length=120, verbose_name='Personne à contacter')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Téléphone')),
                ('phone_secondary', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Téléphone secondaire')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='Ville')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=80, verbose_name='Pays')),
                ('id_kind', models.CharField(blank=True, choices=[('cni', 'CNI'), ('passport', 'Passeport'), ('driver_license', 'Permis de conduire'), ('resident_card', 'Carte de séjour'), ('other', 'Autre')], default='', max_length=20, verbose_name='Type de pièce')),
                ('id_number', models.CharField(blank=True, default='', max_length=80, verbose_name='N° de pièce')),
                ('id_issued_on', models.DateField(blank=True, null=True)),
                ('id_expires_on', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, default='', max_length=120)),
                ('nationality', models.CharField(blank=True, default='Ivoirienne', max_length=80)),
                ('profession', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cni', 'CNI'), ('passport', 'Passeport'), ('driver_license', 'Permis de conduire'), ('resident_card', 'Carte de séjour'), ('sale_contract', 'Contrat de vente signé'), ('purchase_contract', "Contrat d'achat signé"), ('proof_of_address', 'Justificatif de domicile'), ('bank_statement', 'Relevé bancaire'), ('power_of_attorney', 'Procuration'), ('other', 'Autre')], max_length=32, verbose_name='Type')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('file', models.FileField(upload_to=apps.clients.models._client_doc_path)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_name', 'first_name'], name='clients_cli_last_na_198e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='clients_cli_company_9dfa94_idx'),
        ),
    ]
